services:
  laravel:
    build:
      context: laravel
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./laravel/app:/var/www
      - ./laravel/entrypoint.sh:/opt/entrypoint.sh
    # command/entrypoint: see Dockerfile
    command: /bin/bash /opt/entrypoint.sh
    environment:
      SUPERVISOR_PHP_COMMAND: "/usr/bin/php -d variables_order=EGPCS /var/www/html/artisan octane:start --server=frankenphp --host=0.0.0.0 --admin-port=2019 --port=8000" 
      XDG_CONFIG_HOME:  /var/www/html/config 
      XDG_DATA_HOME:  /var/www/html/data
    ports:
      - "8000:8000"
