services:
  laravel:
    build:
      context: .
      dockerfile: docker/laravel/Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    
    volumes:
      - ./laravel:/var/www
      - ./docker/laravel/entrypoint.sh:/opt/entrypoint.sh
      # named volumes exist outside of this folder:
      - vendor:/var/www/vendor
    command: /bin/bash /opt/entrypoint.sh
    env_file:
      - .env
    environment:
      SUPERVISOR_PHP_COMMAND: "/usr/bin/php -d variables_order=EGPCS /var/www/html/artisan octane:start --server=frankenphp --host=0.0.0.0 --admin-port=2019 --port=8000"
      XDG_CONFIG_HOME: /var/www/html/config
      XDG_DATA_HOME: /var/www/html/data
    ports:
      - "8000:8000"
    depends_on:
        bun:
            condition: service_healthy

  bun:
    build:
      context: .
      dockerfile: docker/bun/Dockerfile
    container_name: bundler
    command: ["/bin/bash", "/opt/entrypoint.sh"]
    working_dir: /var/www
    restart: no
    volumes:
        - ./laravel:/var/www
        - ./docker/bun/entrypoint.sh:/opt/entrypoint.sh
        # named volumes exist outside of this folder:
        - node_modules:/var/www/node_modules
    env_file:
      - .env
    healthcheck:
        test: ["CMD", "bash", "-c", "cat /opt/health/status | grep 'ready'"]
        interval: 1s
        timeout: 5s
        retries: 15
        start_period: 0s # no start period bc bun is fast

volumes:
  vendor:
  node_modules: