FROM oven/bun:latest

RUN mkdir /opt/health && mkdir /opt/node_modules

WORKDIR /var/www

# RUN bun install --production
# note: NODE_PATH doesn't seem to work, 
# so bun install happens in entrypoint now.

# command: see docker-compose
